# Generated by Django 2.0.7 on 2018-08-02 13:22

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20180802_2205'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='author',
            field=models.ManyToManyField(related_name='_user_author_+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='user',
            name='reader',
            field=models.ManyToManyField(related_name='_user_reader_+', to=settings.AUTH_USER_MODEL),
        ),
    ]
